[package]
name = "akashic-server"
version = "0.1.0"
edition = "2024"

[dependencies]
akashic-ecs = { path = "../ecs" }
anyhow = { workspace = true }
agent = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rusqlite = { workspace = true }
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
uuid = { version = "1.18.1", features = ["v4"] }

axum = { version = "0.8.8" }
tower-http = { version = "0.6.8", features = ["cors", "trace"] }
flate2 = "1.1.9"
base64 = "0.22.1"
