[package]
name = "akashic"
version = "0.1.0"
edition = "2024"

[dependencies]
agent = { workspace = true }
uuid = { version = "1.8.0", features = ["v4"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
dotenv = { workspace = true }
rand = "0.8.5"
bevy_ecs = "0.18.1"
bevy_tasks = "0.18.1"
