[package]
name = "nodes"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
rig-core = "0.27.0"
flow = { workspace = true }
dotenv = "0.15"
async-trait = "0.1"
ndarray = "0.16.1"
anyhow = "1.0.97"
chrono = "0.4.40"
tracing = { workspace = true }
